apiVersion: apps/v1
kind: Deployment
metadata:
  name: bzion-app
  labels:
    app: bzion-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bzion-app
  template:
    metadata:
      labels:
        app: bzion-app
    spec:
      containers:
        - name: bzion-app
          image: YOUR_DOCKER_IMAGE_HERE # Replace with your Docker image
          ports:
            - containerPort: 3000
