apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bzion-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: your-domain.com # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bzion-app-service
                port:
                  number: 80
